[package]
name = "lea-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0.0"
cipher = "0.3.0"
hex = "0.4.3"
rand = "0.8.5"
arrayvec = "0.5.2"
generic-array = "0.14.4"
