name: "Generic issue"
description: "Open a generic issue for this project"
title: "[Issue] "
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Use this form for any issue that doesn't fit other templates.
  - type: textarea
    id: description
    attributes:
      label: "Issue description"
      description: "Describe your issue in detail."
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: "Additional context"
      description: "Add any other context or information here."
    validations:
      required: false
